trigger: 
  - main

#pool:
 # vmImage: 'ubuntu-latest'
variables:
  app: hostnamectl
stages:
- stage: building_haha
  jobs:
   - job: buildi_babaha
     container: ubuntu:22.04

     #pool:
      #vmImage: 'ubuntu-latest'
     steps:
     - script: |
              $(app)
              cd ~
              ls 
              touch haha
              ls    
              echo "HOSTNAME=$(hostname)"
           
   - job:  build_babaha
    # pool:
     # vmImage: 'windows-2022'
     dependsOn: buildi_babaha
     steps:
     - script: |
              cd ~
              ls 
              echo "HOSTNAME=$(hostname)"










